name: skip-integ-demo
on:
  push:
    branches: [ main ]
    tags: "[0-9]+.[0-9]+.[0-9]+"
  schedule:
    - cron:  '0 15 * * *'
  workflow_dispatch:
  pull_request:

permissions:
  contents: write

jobs:
  call-workflow:
    uses: skiptools/actions/.github/workflows/skip-framework.yml@v1
    #with:
      # skip running local tests because they crash on macos-13
      #run-local-tests: false
      #runs-on: "['macos-13', 'macos-14', 'macos-15']"

