name: skip-integ-demo
on:
  push:
    branches: '*'
    tags: "[0-9]+.[0-9]+.[0-9]+"
  schedule:
    - cron:  '0 7,19 * * *'
  workflow_dispatch:
  pull_request:

permissions:
  contents: write

jobs:
  manual-test:
    runs-on: macos-latest
    steps:
      - name: Cache Homebrew packages
        uses: actions/cache@v4
        with:
          path: ~/Library/Caches/Homebrew
          key: homebrew-packages
      - uses: actions/checkout@v4
      - run: brew install skiptools/skip/skip
      - run: skip android sdk install
      - run: swift test
  call-workflow:
    uses: skiptools/actions/.github/workflows/skip-framework.yml@main
    #with:
      # skip running local tests because they crash on macos-13
      #run-local-tests: false
      #runs-on: "['macos-13', 'macos-14', 'macos-15']"

